name: gonka_wallet
description: "Gonka blockchain wallet"
publish_to: 'none'
version: 1.3.0+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8

  bip39: ^1.0.6
  bip32: ^2.0.0
  pointycastle: ^3.9.1
  bech32: ^0.2.2
  hex: ^0.2.0
  convert: ^3.1.0
  crypto: ^3.0.6
  protobuf: ^3.1.0
  fixnum: ^1.1.0

  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  no_screenshot: ^0.3.0
  root_jailbreak_sniffer: ^1.1.3

  dio: ^5.7.0

  flutter_riverpod: ^2.6.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  go_router: ^14.6.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0
  flutter_svg: ^2.2.4
  url_launcher: ^6.3.2
  reown_walletkit: ^1.3.8
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  ios: false
  android: false
  macos:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.svg
